### ISSUE TITLE
add the index.html 

### ISSUE THREAD

**Issue by SagnikDeshmukh** [SagnikDeshmukh/MAKAUT_Organiser#1]
In this you need to add the basic html code required you can start from scratch or just wait for sometime as i will be giving the figma design

**Comment by PriyanshuPaul79** [comment]
can i help ? assign me

**Comment by seabeePraveen** [comment]
hii @SagnikDeshmukh i have a good experience with both frontend and backend u check my profile if u want and i will complete this work very soon if u provide the correct resources
