### ISSUE TITLE
[Bug]: useless text added with logo

### ISSUE THREAD

**Issue by PankajKumar1947** [SagnikDeshmukh/MAKAUT_Organiser#29]
there is a extra word 'hello' with the logo which should not be there
--see the below image
![Screenshot (57)_LI](https://github.com/SagnikDeshmukh/MAKAUT_Organiser/assets/130830370/75408227-78fc-4be1-b953-b53fb90a20ff)

**Comment by babitakry** [comment]
assign me issue no. #29
